language: java

sudo: false

env:
  global:
  - CODECOV_TOKEN="9b8ed8c4-920a-41c5-b122-c6d0d65915e4"

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  emails:
    recipients:
      -marcos.barra@zup.com.br
    on_success: always
    on_failure: always